CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    DOCUMENT VARCHAR(11),
    EMAIL VARCHAR(100)
);

CREATE TABLE GAMES (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    DESCRIPTION VARCHAR(100),
    NOTE INT
);